### PR TITLE
feat: adds BaseTreeRepository

### PR DESCRIPTION
**Pull request by daffodil11**
Adds BaseTreeRepository, which extends typeorm's TreeRepository, in order to support use of TreeEntities.

### CODE REVIEW

**Comment by odavid** [comment]
Hi @daffodil11, 
Thank you for the contribution!

I think it will be also nice to have additional `patch` method for the `TreeRepository` like this:

https://github.com/odavid/typeorm-transactional-cls-hooked/blob/master/src/patch-typeorm-repository.ts#L4

Other than that lgtm.

What do you think?

**Comment by daffodil11** [comment]
Hi, @odavid . Good point!

Does that look OK to you?

**Comment by odavid** [comment]
Thanks @daffodil11 
lgtm!
Can you just enhance the README with the changes?

**Comment by daffodil11** [comment]
Hi, @odavid . I've added some documentation about the changes in the README. Is it sufficient?

**Comment by odavid** [comment]
@daffodil11 - again, thank you for this contribution!

**Comment by daffodil11** [comment]
@odavid Thank you, too! It's a very useful library. Also, this is my first contribution to OSS, so I appreciate how helpful and polite you've been.

Keep up the good work!

**Pull request merged**
